# Default values for nginx-file-browser.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx #镜像名称
  pullPolicy: IfNotPresent #拉取策略
  # Overrides the image tag whose default is the chart appVersion.
  tag: "alpine" #镜像版本

podAnnotations: {}  #pod元数据

service:
  type: ClusterIP
  port: 80
  nodePort: 00000

nfs:
  enabled: false
  path: /mnt/data  #nfs挂载目录
  server:  127.0.0.1 #nfs共享目录ip地址


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
