apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-file-browser.fullname" . }}
  labels:
    {{- include "nginx-file-browser.labels" . | nindent 4 }}
data:
  nginx.conf: |-
{{- if .Values.nginxConfOverride }}
{{ tpl .Values.nginxConfOverride . | indent 4 }}
{{- else }}
{{ .Files.Get "files/nginx.conf" | indent 4 }}
{{- end }}