{{- if eq .Values.service.type "ClusterIP" }}
{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
  name: {{ include "springboot-app.fullname" . }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "springboot-app.fullname" . }}
              servicePort: {{ .Values.service.port }}
      host: {{ include "name" . }}.{{ include "namespace" . }}.{{ .Values.ingress.nodeHost }}.nip.io    
{{- end }}  
{{- end }} 

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ include "name" . }}
  namespace: {{ include "namespace" . }}
  labels:
     {{- include "springboot-app.labels" . | nindent 4 }}
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  selector:
    matchLabels:
      {{- include "springboot-app.selectorLabels" . | nindent 6 }}
  addOwnerRef: true
  descriptor:
  componentKinds:
    - group: ''
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: extensions
      kind: Ingress
    - group: servicemesh.kubesphere.io
      kind: Strategy
    - group: servicemesh.kubesphere.io
      kind: ServicePolicy