apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ include "name" . }}
  namespace: {{ include "namespace" . }}
  labels:
     {{- include "springboot-app.labels" . | nindent 4 }}
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  selector:
    matchLabels:
      {{- include "springboot-app.selectorLabels" . | nindent 6 }}
  addOwnerRef: true
  descriptor:
  componentKinds:
    - group: ''
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: extensions
      kind: Ingress
    - group: servicemesh.kubesphere.io
      kind: Strategy
    - group: servicemesh.kubesphere.io
      kind: ServicePolicy