apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-app.fullname" . }}
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "springboot-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "springboot-app.selectorLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.mesh.enable }}
        sidecar.istio.io/inject: 'true'
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "springboot-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      {{- if .Values.skyWalking.enable }}
      - name: sidecar
        image: apache/skywalking-java-agent:8.13.0-java8 # 容器镜像，包含静态资源文件
        imagePullPolicy: IfNotPresent
        command: ["cp", "-r", "/skywalking/agent", "/sidecar"]
        volumeMounts:
          - name: sidecar
            mountPath: /sidecar
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_NAME
              value: {{ include "springboot-app.fullname" . }}
            {{- if .Values.mesh.enable }}
            - name: POD_NAMESPACE #dubbo mesh 需要
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: dubbo.registry.address #mesh关闭注册中心
              value: N/A
            {{- end }}
            {{- if .Values.debug.enable }}
            - name: DEBUG_OPTS
              value:  {{ .Values.debug.opts }}
            {{- end }}
            {{- if .Values.skyWalking.enable }}
            - name: JAVA_OPTS
              value: -javaagent:/sidecar/agent/skywalking-agent.jar
            - name: SW_AGENT_NAME
              value: {{ include "springboot-app.fullname" . }} #服务名
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "{{.Values.skyWalking.oap}}" # skywalk oap 后端服务
            {{- end }}
          ports:
            - name: http-web
              containerPort: {{ .Values.web.port }}
              protocol: TCP
            {{- if .Values.dubbo.enable }}
            - name: dubbo
              containerPort: {{ .Values.dubbo.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.debug.enable }}
            - name: remote-debug
              containerPort: 5005
              protocol: TCP,UDP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.skyWalking.enable }}
          volumeMounts:
            - name: sidecar
              mountPath: /sidecar
          {{- end }}
      {{- if .Values.skyWalking.enable }}
      volumes:
        - name: sidecar  #共享agent文件夹
          emptyDir: {}
      {{- end }}