apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-{{ .Values.service.port }}
      port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      {{- if ne "0" (toString .Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
  selector:
    {{- include "springboot-app.selectorLabels" . | nindent 4 }}