{{- if .Values.web.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}-web
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'  
spec:
  type: {{ .Values.web.type }}
  ports:
    - name: http-web
      port: {{ .Values.web.port }}
      {{- if eq .Values.web.type "NodePort" }}
      {{- if ne "0" (toString .Values.web.nodePort) }}
      nodePort: {{ .Values.web.nodePort }}
      {{- end }}
      {{- end }}
  selector:
    {{- include "springboot-app.selectorLabels" . | nindent 4 }}
{{- end }}
--- 

{{- if .Values.dubbo.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  type: {{ .Values.dubbo.type }}
  ports:
    - name: http-dubbo
      port: {{ .Values.dubbo.port }}
      targetPort: {{ .Values.dubbo.port }}
      protocol: TCP
      {{- if eq .Values.dubbo.type "NodePort" }}
      {{- if ne "0" (toString .Values.dubbo.nodePort) }}
      nodePort: {{ .Values.dubbo.nodePort }}
      {{- end }}
      {{- end }}
  selector:
    {{- include "springboot-app.selectorLabels" . | nindent 4 }}
{{- end }}
---

{{- if .Values.debug.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}-debug
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  type: NodePort
  ports:
    - name: http-debug
      port:  {{ .Values.debug.port }}
      targetPort: {{ .Values.debug.port }}
      protocol: TCP
      nodePort: {{ .Values.debug.port }}
  selector:
    {{- include "springboot-app.selectorLabels" . | nindent 4 }}
{{- end }}
---    