apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'  
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-{{ .Values.service.port }}
      port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      {{- if ne "0" (toString .Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
  selector:
    {{- include "springboot-app.selectorLabels" . | nindent 4 }}
--- 

{{- if .Values.dubboservice.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "preName" . }}-dubbo-provider
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "serviceLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
spec:
  type: {{ .Values.dubboservice.type }}
  ports:
    - name: http-{{ .Values.dubboservice.port }}
      port: {{ .Values.dubboservice.port }}
      targetPort: {{ .Values.dubboservice.port }}
      protocol: TCP
      {{- if eq .Values.dubboservice.type "NodePort" }}
      {{- if ne "0" (toString .Values.dubboservice.nodePort) }}
      nodePort: {{ .Values.dubboservice.nodePort }}
      {{- end }}
      {{- end }}
  sessionAffinity: None
  selector:
    {{- include "serviceLabels" . | nindent 4 }}
{{- end }}
---    